# Generated by Django 4.1.1 on 2022-09-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_blog',
            name='Author',
            field=models.CharField(max_length=100),
        ),
    ]
